// Copies the Remix Icons the extension actually uses into lib/icons.tsx.
//
// @remixicon/react ships every icon (~3,000) in one 2.4 MB file that the
// bundler can't trim, so importing it directly bloats the popup. This
// script finds every `Ri…` icon named in components/, lib/ and tabs/,
// renders each one once, and writes just those shapes out.
//
// Run it after using a new icon:  pnpm --filter extension icons
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs"
import { createRequire } from "node:module"
import { join } from "node:path"

const require = createRequire(import.meta.url)
const React = require("react")
const { renderToStaticMarkup } = require("react-dom/server")
const Icons = require("@remixicon/react")

const root = new URL("..", import.meta.url).pathname
const out = join(root, "lib/icons.tsx")

function files(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name)
    if (statSync(path).isDirectory()) return files(path)
    return /\.tsx?$/.test(name) && path !== out ? [path] : []
  })
}

const used = new Set()
for (const dir of ["components", "lib", "tabs"]) {
  for (const file of files(join(root, dir))) {
    for (const match of readFileSync(file, "utf8").matchAll(/\bRi[A-Z][A-Za-z0-9]+\b/g)) {
      used.add(match[0])
    }
  }
}

const names = [...used].filter((n) => n in Icons).sort()
const entries = names.map((name) => {
  const svg = renderToStaticMarkup(React.createElement(Icons[name]))
  const inner = svg.replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "")
  return `export const ${name} = icon(${JSON.stringify(inner)})`
})

writeFileSync(
  out,
  `// Generated by scripts/build-icons.mjs — don't edit by hand.
// Run \`pnpm --filter extension icons\` after using a new Remix Icon.
import type { SVGProps } from "react"

type Props = { size?: number | string; className?: string } & Omit<SVGProps<SVGSVGElement>, "ref">

function icon(paths: string) {
  return function Icon({ size = 24, className, ...rest }: Props) {
    return (
      <svg
        viewBox="0 0 24 24"
        width={size}
        height={size}
        fill="currentColor"
        aria-hidden="true"
        className={className}
        dangerouslySetInnerHTML={{ __html: paths }}
        {...rest}
      />
    )
  }
}

${entries.join("\n")}
`
)
console.log(`Wrote ${names.length} icons to lib/icons.tsx`)
